-- V12__CREATE_USERS_ROLES_TABLE.sql

CREATE TABLE user_roles
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USERS_ROLES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_USERS_ROLES_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);