-- V1__CREATE_TABLES_INITIAL.sql

-- Create Users table
CREATE TABLE USERS
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

-- Create Authors table
CREATE TABLE AUTHORS
(
    ID         BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    BIRTH_DATE DATE,
    BIOGRAPHY  VARCHAR(255)
);

-- Create Books table
CREATE TABLE BOOKS
(
    ID        BIGSERIAL PRIMARY KEY,
    TITLE     VARCHAR(255),
    AUTHOR_ID BIGINT,
    CONSTRAINT FK_BOOKS_AUTHORS_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID)
);

-- Create Categories table
CREATE TABLE CATEGORIES
(
    ID    BIGSERIAL PRIMARY KEY,
    GENRE VARCHAR(255)
);

-- Create Books_Categories table
CREATE TABLE BOOKS_CATEGORIES
(
    BOOK_ID     BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CONSTRAINT FK_BOOKS_CATEGORIES_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
    CONSTRAINT FK_BOOKS_CATEGORIES_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID)
);

-- Create Borrowing_History table
CREATE TABLE BORROWING_HISTORY
(
    ID               BIGSERIAL PRIMARY KEY,
    BORROWED_BOOK_ID BIGINT,
    BORROWER_ID      BIGINT,
    BORROWED_DATE    TIMESTAMP,
    CONSTRAINT FK_BORROWING_HISTORY_BOOK_ID FOREIGN KEY (BORROWED_BOOK_ID) REFERENCES books (ID),
    CONSTRAINT FK_BORROWING_HISTORY_USER_ID FOREIGN KEY (BORROWER_ID) REFERENCES users (ID)
);