-- V3__ADD_CONSTRAINTS_TO_COLUMNS.sql

ALTER TABLE BORROWING_HISTORY
    ALTER COLUMN BORROWED_DATE SET NOT NULL;

ALTER TABLE BORROWING_HISTORY
    ALTER COLUMN BORROWER_ID SET NOT NULL;

ALTER TABLE BORROWING_HISTORY
    ALTER COLUMN BORROWED_BOOK_ID SET NOT NULL;

ALTER TABLE AUTHORS
    ALTER COLUMN FIRST_NAME SET NOT NULL;

ALTER TABLE AUTHORS
    ALTER COLUMN LAST_NAME SET NOT NULL;

ALTER TABLE AUTHORS
    ALTER COLUMN BIRTH_DATE SET NOT NULL;

ALTER TABLE BOOKS
    ALTER COLUMN TITLE SET NOT NULL;

ALTER TABLE CATEGORIES
    ALTER COLUMN GENRE SET NOT NULL;

ALTER TABLE USERS
    ALTER COLUMN NAME SET NOT NULL;