-- V9__ADD_ROLES_TABLE.sql

CREATE TABLE ROLES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    USER_ID BIGINT,
    CONSTRAINT FK_ROLES_ID_USERS_ID
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID),
    CONSTRAINT UNIQUE_CONSTRAINT_ROLE_NAME
        UNIQUE (NAME)
);